apps/rule_sets.py
Requires: https://github.com/superdesk/superdesk-client/pull/674
=> (improvement) New Attribute of a Rule should allow empty string

apps/archive/archive.py, apps/archive/archive_media.py, apps/archive/common.py, features/archive.feature
Is required by https://github.com/superdesk/superdesk-client/pull/675
=> (fix) SD-1320, SD-1321

README.md
registered on [landscape](https://landscape.io/github/superdesk/superdesk-server)
=> feat(landscape): add code health status badge to readme

apps/archive/archive_media.py, superdesk/media/media_operations.py, superdesk/upload.py
related to https://dev.sourcefabric.org/browse/LBSD-283
=> file upload : Handle heavy files

apps/archive/__init__.py, apps/archive/archive.py, apps/archive/archive_spike.py, apps/archive/archive_test.py, apps/desks.py, apps/stages.py, apps/tasks.py, apps/tasks_tests.py, features/stages.feature, settings.py
This PR includes changes for the task [SD-1323] Schema change for desk and stage expiry as well.
I will be adding few more tests to check the expiry when content is submitted to a desk or when the stage is changed. 
Also the filter query that gets all expired content will be tested.
=> [SD-1324] Stage and Desk level expriy

.travis.yml
it should make travis builds run faster
=> feat(travis): use docker based builds

features/steps/steps.py, superdesk/io/commands/update_ingest.py, superdesk/io/commands/update_ingest_tests.py
SD-1228.
Rebase with master. Use this PR.
=> (feat) Ingest configurations should be committed gracefully

superdesk/io/commands/remove_expired_content.py, superdesk/io/ingest_service.py
+ workaround for eve serialization issue affecting `is_closed`
SD-1125
=> fix(ingest): remove only 100 items at a time

apps/auth/ldap/ldap.py
=> (fix)user: fixing the status code returned by API in case of wrong credentials.

superdesk/errors.py, superdesk/io/commands/update_ingest.py
There were few Sentry logs on the weekend regarding an error in raising Provider error in ingest.
=> [SD-1357] Ingest service failed to throw ingest error

apps/archive/archive.py, superdesk/etree.py, superdesk/io/__init__.py, superdesk/io/io_tests.py, superdesk/io/nitf.py
In order to cut the dependence between archive and io I moved the
get_word_count function on etree module.
=> chore(word counts) - Moved the word counts on etree module

apps/content.py, apps/coverages.py, apps/stages.py, apps/users/users.py, features/activity.feature, features/packages.feature, features/rule_sets.feature, features/stages.feature, features/steps/steps.py, features/user.feature, requirements.txt, settings.py, superdesk/io/ingest_provider_model.py
=> chore(eve) - upgrade Eve to 0.5

ws.py
so we will know from what instance we get it
=> feat(ws): add server info to heartbeat

apps/archive/archive.py, apps/item_lock/components/item_lock.py, features/archive.feature
=> (fix) Fixing notifications for lock and unique name permissions.

apps/archive/archive.py, apps/archive/common.py, apps/search/__init__.py, apps/stages.py, apps/users/services.py, features/search.feature, features/stages.feature, features/steps/steps.py, features/user.feature
=> (feat)Stages - Implemented invisible stage.

apps/archive/archive.py, apps/archive/archive_media.py, apps/archive/archive_spike.py, apps/archive/common.py, apps/stages.py, apps/tasks.py, apps/tasks_tests.py, features/archive.feature, features/content_spike.feature, features/search.feature, features/stages.feature, features/steps/steps.py, superdesk/tests.py, superdesk/utc.py, superdesk/utc_tests.py
[SD-1442] Sliding Expiry
Expiry value of the content item will be reset when:
- Content is created/fetched
- Content is updated
- Content is sent to a desk/stage/workspace
- Spiked/Unspiked
[SD-1452] Updating expiry
- Expiry value of the content items in a stage will be reset when the stage expiry value is updated.
=> [SD-1442] Implement sliding expiry for content items

apps/highlights/__init__.py, apps/highlights/resource.py, apps/highlights/service.py, features/highlights.feature, settings.py
Create, Edit, Delete highlights
Mark items for a highlights
=> feat(Highlights): Base highlights

apps/archive/archive.py, apps/archive/common.py
so that client can detect changes to a specific item
=> feat(archive): add item id to update notification

apps/stages.py, features/stages.feature
SD-1485, SD-1486
Push notification in case of
- on change of stage Global Read flag.
- on change of Content Expiry.
=> (feat)[Stages]: Stage:update notifications

apps/archive/archive_ingest.py, features/archive_ingest.feature, features/ingest.feature, features/steps/steps.py, superdesk/io/commands/remove_expired_content.py, superdesk/io/commands/update_ingest.py, superdesk/io/reuters.py
Refactor how ingesting is done.
Fix fetching items from ingest.
=> SD-1451 Problem with ingest for composite items

apps/stages.py, features/stages.feature
=> (Fix)[Stage] Added stage is_visible flag to the notification and fixed the condition.

superdesk/media/renditions.py, superdesk/upload.py
- set quality and antialiasing for thumbnails
- let browsers cache images
=> fix(upload): improve image quality for thumbnails

features/steps/steps.py, superdesk/errors.py, superdesk/io/__init__.py, superdesk/io/fixtures/wenn.xml, superdesk/io/newsml_2_0.py, superdesk/io/wenn_parser.py, superdesk/io/wenn_parser_test.py
=> (feat)[ingest] WENN parser for parsing WENN feed

apps/archive/__init__.py, apps/archive/archive.py, apps/archive/archive_test.py, apps/archive/commands.py, requirements.txt, superdesk/__init__.py, superdesk/commands.py, superdesk/commands_tests.py
Depends on https://github.com/petrjasek/eve-elastic/pull/27
=> feat(rebuild index) - add "app:rebuild_elastic_index" command

apps/packages/service.py, features/packages.feature
=> fix(packages) - update two way link when a reference is removed

superdesk/io/__init__.py, superdesk/io/anpa.py, superdesk/io/io_tests.py, superdesk/io/newsml_1_2.py, superdesk/io/newsml_2_0.py, superdesk/io/nitf.py
Reverting the earlier changes done to trim the headline and slugline fields.
=> [SD-1482] Remove the truncation of the headlines from ingest

apps/archive/archive.py
fix filter when there are some non-visible stages
=> fix(content): fix private content filtering

apps/desks.py, apps/stages.py, features/desks.feature, features/stages.feature
Send events/notifications on changes to desks/stages.
=> [SD-1511] Add events for desk/stage changes

settings.py, superdesk/celery_app.py, superdesk/celery_tests.py, superdesk/io/__init__.py, superdesk/io/commands/update_ingest.py, superdesk/io/commands/update_ingest_tests.py, superdesk/io/ftp.py
call `update_provider.delay` + fix an issue with `celery.loads`
=> fix(ingest): run each provider update on its own worker
